class packages {
include apt

package {
    [ 'awscli',
      'ack-grep',
      'bogofilter-common',
      'bogofilter-sqlite',
      'build-essential',
      'checkinstall',
      'curl',
      'conky',
      'dropbox',
      'etherape',
      'evolution',
      'evolution-ews',
      'fdupes',
      'findutils',
      'html2text',
      'inkscape',
      'jq',
      'keepassx',
      'libxml2-utils',
      'meld',
      'nmap',
      'openconnect',
      'openssh-server',
      'password-gorilla',
      'pianobar',
      'python-lxml',
      'tar',
      'tmux',
      'tofrodos',
      'tig',
      'traceroute',
      'ubuntu-restricted-extras',
      'vim',
      'virtualenv',
      'xchat',
      'xtightvncviewer',
      'xfce4-clipman-plugin',
    ]:
  }
}
